name: Bug Report
description: File a bug report
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Tell us what happened.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behavior
      description: Tell us what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce this bug.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Crash/Log output
      description: Please copy and paste any error messages or logs relevant to this bug.
      render: shell
  - type: markdown
    attributes:
      value: |
        Thanks again for taking the time to fill out this form! 
        Before posting this issue, please make sure that everything is detailed and clear, and you have not missed any details.
