blank_issues_enabled: false
contact_links:
  - name: Do you need help or have a question?
    about: You can ask questions in the "Help / Q&A" category in GitHub Discussions
    url: https://github.com/zeke-io/endline/discussions/categories/help-q-a
  - name: Feature requests
    about: Find or create feature requests in the "Ideas" category in GitHub Discussions
    url: https://github.com/zeke-io/endline/discussions/categories/ideas
