on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

name: Build and Test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
      - uses: actions/cache@v3
        id: build-cache
        with:
          path: ./*
          key: build-${{ github.run_number }}-${{ github.sha }}

      - run: pnpm install
      - run: pnpm build

  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          check-latest: true
      - uses: actions/cache@v3
        id: restore-build-cache
        with:
          path: ./*
          key: build-${{ github.run_number }}-${{ github.sha }}

      - run: pnpm prettier:check
      - run: pnpm lint:check

  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          check-latest: true
      - uses: actions/cache@v3
        id: restore-build-cache
        with:
          path: ./*
          key: build-${{ github.run_number }}-${{ github.sha }}

      - run: pnpm test
