name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.5.0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/cache@v3
        id: build-cache
        with:
          path: ./*
          key: build-${{ github.run_number }}-${{ github.sha }}

      - run: bun run install
      - run: bun run build

  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.5.0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/cache@v3
        id: restore-build-cache
        with:
          path: ./*
          key: build-${{ github.run_number }}-${{ github.sha }}

      - run: bun run prettier:check
      - run: bun run type:check
      - run: bun run lint:check

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.5.0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/cache@v3
        id: restore-build-cache
        with:
          path: ./*
          key: build-${{ github.run_number }}-${{ github.sha }}

      - run: bun run test
