name: Publish package to npm

on:
  workflow_dispatch:
    inputs:
      semver:
        description: Version to increase
        required: true
        type: choice
        options:
          - major
          - minor
          - patch


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - run: pnpm install
      - run: pnpm build
      - run: pnpm types

      - name: "Version and Publish"
        env:
          SEMVER_TYPE: ${{ inputs.semver }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          lerna version $SEMVER_TYPE --yes

          lerna publish from-git --yes
